[package]
name = "debug_renderer"
version = "0.1.0"
authors = ["Issaadi Sami <sami.issaadi@epita.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kiss3d = "0.24.1"
nalgebra = "0.21.0"
